Repository bumble-tech/appyx, pull requests merged in 2022-08, with the labels that each got.

#51 Created publish plugin
  RELEASING.md
  core/build.gradle
  customisations/build.gradle
  gradle.properties
  gradle/libs.versions.toml
  gradle/publication.gradle
  interop-ribs/build.gradle
  interop-rx2/build.gradle
  plugins/publish-plugin/build.gradle.kts
  plugins/publish-plugin/settings.gradle.kts
  plugins/publish-plugin/src/main/kotlin/AndroidAppyxPublishPlugin.kt
  plugins/publish-plugin/src/main/kotlin/AppyxPublishPlugin.kt
  plugins/publish-plugin/src/main/kotlin/JavaAppyxPublishPlugin.kt
  routing-source-addons/build.gradle
  settings.gradle
  testing-junit4/build.gradle
  testing-junit5/build.gradle
  testing-ui/build.gradle
  testing-unit-common/build.gradle
Labels: enhancement

#72 Fixed existing detekt/lint issues
  app/detekt-baseline.xml
  app/detekt.yml
  app/lint-baseline.xml
  app/lint.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/bumble/appyx/app/node/onboarding/screen/ApplicationTree.kt
  app/src/main/java/com/bumble/appyx/app/node/onboarding/screen/StatefulNode2.kt
  app/src/main/java/com/bumble/appyx/app/node/teaser/backstack/transitionhandler/CustomBackStackTransitionHandler.kt
  app/src/main/java/com/bumble/appyx/app/node/teaser/promoter/PromoterTeaserNode.kt
  app/src/main/res/drawable-xxxhdpi/appyx.png
  app/src/main/res/drawable-xxxhdpi/appyx_text_black_s.png
  app/src/main/res/drawable-xxxhdpi/appyx_text_white_s.png
  app/src/main/res/mipmap-anydpi-v26/appyx.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
  core/detekt-baseline.xml
  core/lint-baseline.xml
  core/src/main/java/com/bumble/appyx/core/builder/Builder.kt
  core/src/main/java/com/bumble/appyx/core/builder/SimpleBuilder.kt
  core/src/main/java/com/bumble/appyx/core/composable/Children.kt
  core/src/main/java/com/bumble/appyx/core/integration/NodeFactory.kt
  core/src/main/java/com/bumble/appyx/core/integration/NodeHost.kt
  core/src/main/java/com/bumble/appyx/core/node/Node.kt
  core/src/main/java/com/bumble/appyx/core/routing/BaseRoutingSource.kt
  core/src/main/java/com/bumble/appyx/debug/Appyx.kt
  core/src/main/java/com/bumble/appyx/routingsource/backstack/operation/Replace.kt
  core/src/main/java/com/bumble/appyx/routingsource/spotlight/operation/Previous.kt
  core/src/main/java/com/bumble/appyx/routingsource/spotlight/transitionhandler/SpotlightFader.kt
  core/src/test/java/com/bumble/appyx/core/children/ChildAwareTestBase.kt
  core/src/test/java/com/bumble/appyx/routingsource/backstack/operation/BackStackTestHelper.kt
  core/src/test/java/com/bumble/appyx/routingsource/backstack/operation/Routing.kt
  detekt.yml
  interop-ribs/detekt-baseline.xml
  interop-ribs/src/main/java/com/bumble/appyx/interop/ribs/InteropNode.kt
  interop-ribs/src/main/java/com/bumble/appyx/interop/ribs/InteropView.kt
  interop-rx2/detekt-baseline.xml
  interop-rx2/src/test/java/com/bumble/appyx/connectable/rx2/Rx2NodeConnectorTest.kt
  plugins/verification-plugin/src/main/kotlin/DetektPlugin.kt
  sandbox/detekt-baseline.xml
  sandbox/detekt.yml
  sandbox/lint-baseline.xml
  sandbox/lint.xml
  sandbox/src/main/AndroidManifest.xml
  sandbox/src/main/res/values/themes.xml
  sandbox/src/test/java/com/bumble/appyx/sandbox/stub/FeatureStub.kt
  testing-junit5/detekt-baseline.xml
  testing-junit5/src/main/java/com/bumble/appyx/testing/junit5/util/CoroutinesTestExtension.kt
  testing-ui/detekt-baseline.xml
  testing-ui/src/main/java/com/bumble/appyx/testing/ui/rules/AppyxTestRule.kt
  testing-unit-common/detekt-baseline.xml
  testing-unit-common/src/main/java/com/bumble/appyx/testing/unit/common/helper/InteractorTestHelper.kt
Labels: bug, enhancement

#74 Fix Detekt SARIF reports
  plugins/verification-plugin/src/main/kotlin/CollectSarifPlugin.kt
Labels: Build & CI

#70 [#69] Created Jetpack compose navigation sample
  CHANGELOG.md
  core/src/main/java/com/bumble/appyx/core/integrationpoint/LocalIntegrationPoint.kt
  documentation/how-to-use-appyx/sample-apps.md
  gradle/libs.versions.toml
  samples/navigation-compose/README.md
  samples/navigation-compose/build.gradle
  samples/navigation-compose/lint-baseline.xml
  samples/navigation-compose/src/androidTest/java/com/bumble/appyx/sample/navigtion/compose/ComposeNavigationActivityTest.kt
  samples/navigation-compose/src/main/AndroidManifest.xml
  samples/navigation-compose/src/main/java/com/bumble/appyx/sample/navigtion/compose/ComposeNavigationActivity.kt
  samples/navigation-compose/src/main/java/com/bumble/appyx/sample/navigtion/compose/ComposeNavigationContainerNode.kt
  samples/navigation-compose/src/main/java/com/bumble/appyx/sample/navigtion/compose/ComposeNavigationRoot.kt
  samples/navigation-compose/src/main/res/mipmap-hdpi/ic_launcher.webp
  samples/navigation-compose/src/main/res/mipmap-mdpi/ic_launcher.webp
  samples/navigation-compose/src/main/res/mipmap-xhdpi/ic_launcher.webp
  samples/navigation-compose/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  samples/navigation-compose/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  samples/navigation-compose/src/main/res/values/strings.xml
  settings.gradle
Labels: documentation, enhancement

#65 Add interop builder stub
  CHANGELOG.md
  gradle/libs.versions.toml
  interop-ribs/src/main/java/com/bumble/appyx/interop/ribs/InteropNode.kt
  interop-ribs/src/main/java/com/bumble/appyx/interop/ribs/InteropView.kt
  sandbox/build.gradle
  sandbox/src/main/java/com/bumble/appyx/sandbox/MainActivity.kt
  sandbox/src/main/java/com/bumble/appyx/sandbox/client/container/ContainerBuilder.kt
  sandbox/src/main/java/com/bumble/appyx/sandbox/client/container/ContainerNode.kt
  sandbox/src/main/java/com/bumble/appyx/sandbox/client/interop/child/RibsChildBuilder.kt
  sandbox/src/main/java/com/bumble/appyx/sandbox/client/interop/child/RibsChildNode.kt
  sandbox/src/main/java/com/bumble/appyx/sandbox/client/interop/parent/RibsParentBuilder.kt
  sandbox/src/main/java/com/bumble/appyx/sandbox/client/interop/parent/RibsParentInteractor.kt
  sandbox/src/main/java/com/bumble/appyx/sandbox/client/interop/parent/RibsParentRib.kt
  sandbox/src/main/java/com/bumble/appyx/sandbox/client/interop/parent/routing/RibsParentChildBuilders.kt
  sandbox/src/main/java/com/bumble/appyx/sandbox/client/interop/parent/routing/RibsParentRouter.kt
  sandbox/src/test/java/com/bumble/appyx/sandbox/client/interop/parent/RibsParentNodeTest.kt
  testing-unit-common/src/main/java/com/bumble/appyx/testing/unit/common/util/InteropBuilderStub.kt
  testing-unit-common/src/main/java/com/bumble/appyx/testing/unit/common/util/InteropSimpleBuilderStub.kt
  testing-unit-common/src/main/java/com/bumble/appyx/testing/unit/common/util/NodeStub.kt
Labels: enhancement

#61 [bumble-tech#59] Added interface for ParentNodeView
  CHANGELOG.md
  core/src/main/java/com/bumble/appyx/core/node/AbstractParentNodeView.kt
  core/src/main/java/com/bumble/appyx/core/node/EmptyNodeViews.kt
  core/src/main/java/com/bumble/appyx/core/node/ParentNodeView.kt
  sandbox/src/main/java/com/bumble/appyx/sandbox/client/mvicoreexample/MviCoreExampleView.kt
  sandbox/src/test/java/com/bumble/appyx/sandbox/stub/NodeViewStub.kt
Labels: enhancement

#82 Remove assumption that there can be only one root from IntegrationPoint
  CHANGELOG.md
  core/src/main/java/com/bumble/appyx/core/integration/NodeHost.kt
  core/src/main/java/com/bumble/appyx/core/integrationpoint/IntegrationPoint.kt
Labels: enhancement

#92 Spotlight Next and Previous operations crash fix.
  CHANGELOG.md
  core/src/main/java/com/bumble/appyx/navmodel/spotlight/operation/Next.kt
  core/src/main/java/com/bumble/appyx/navmodel/spotlight/operation/Previous.kt
  core/src/test/java/com/bumble/appyx/navmodel/spotlight/SpotlightTestHelper.kt
  core/src/test/java/com/bumble/appyx/navmodel/spotlight/operation/NextTest.kt
  core/src/test/java/com/bumble/appyx/navmodel/spotlight/operation/PreviousTest.kt
  core/src/test/java/com/bumble/appyx/navmodel/spotlight/operation/Routing.kt
Labels: bug
