Repository bumble-tech/appyx, pull requests merged in 2022-10, with the labels that each got.

#197 Remove plugin implementation from view and retrieve node instance from LocalComposition
  CHANGELOG.md
  libraries/core/src/androidTest/kotlin/com/bumble/appyx/core/plugin/AppyxTestScenario.kt
  libraries/core/src/androidTest/kotlin/com/bumble/appyx/core/plugin/BackPressHandlerTestActivity.kt
  libraries/core/src/main/kotlin/com/bumble/appyx/core/node/AbstractParentNodeView.kt
  libraries/core/src/main/kotlin/com/bumble/appyx/core/node/EmptyNodeViews.kt
  libraries/core/src/main/kotlin/com/bumble/appyx/core/node/ParentNode.kt
  libraries/core/src/main/kotlin/com/bumble/appyx/core/node/ParentNodeView.kt
  libraries/testing-ui-activity/src/main/AndroidManifest.xml
  libraries/testing-ui-activity/src/main/kotlin/com/bumble/appyx/testing/ui/rules/AppyxTestActivity.kt
  libraries/testing-ui/src/main/kotlin/com/bumble/appyx/testing/ui/rules/AppyxActivityTestRule.kt
  libraries/testing-ui/src/main/kotlin/com/bumble/appyx/testing/ui/rules/AppyxParentViewTestRule.kt
  libraries/testing-ui/src/main/kotlin/com/bumble/appyx/testing/ui/rules/AppyxViewTestRule.kt
  libraries/testing-ui/src/main/kotlin/com/bumble/appyx/testing/ui/utils/DummyNavModel.kt
  samples/sandbox/src/androidTest/kotlin/com/bumble/appyx/sandbox/client/mvicoreexample/MviCoreExampleViewTest.kt
  samples/sandbox/src/androidTest/kotlin/com/bumble/appyx/sandbox/client/test/AppyxMviParentViewTestRule.kt
  samples/sandbox/src/androidTest/kotlin/com/bumble/appyx/sandbox/client/test/AppyxViewRules.kt
  samples/sandbox/src/main/kotlin/com/bumble/appyx/sandbox/client/mvicoreexample/MviCoreExampleView.kt
  samples/sandbox/src/test/kotlin/com/bumble/appyx/sandbox/stub/NodeViewStub.kt
Labels: api-breaking

#212 Make Node's parent property as public
  CHANGELOG.md
  libraries/core/src/main/kotlin/com/bumble/appyx/core/node/Node.kt
Labels: invalid

#202 Sandbox cleanup - extract logic from ContainerNode to standalone Nodes
  gradle/libs.versions.toml
  samples/sandbox/build.gradle.kts
  samples/sandbox/src/main/kotlin/com/bumble/appyx/sandbox/MainActivity.kt
  samples/sandbox/src/main/kotlin/com/bumble/appyx/sandbox/TextButton.kt
  samples/sandbox/src/main/kotlin/com/bumble/appyx/sandbox/client/container/ContainerNode.kt
  samples/sandbox/src/main/kotlin/com/bumble/appyx/sandbox/client/customisations/CustomisationsNode.kt
  samples/sandbox/src/main/kotlin/com/bumble/appyx/sandbox/client/interactorusage/InteractorExample.kt
  samples/sandbox/src/main/kotlin/com/bumble/appyx/sandbox/client/interactorusage/InteractorExampleChildrenNode.kt
  samples/sandbox/src/main/kotlin/com/bumble/appyx/sandbox/client/interactorusage/InteractorExampleNode.kt
  samples/sandbox/src/main/kotlin/com/bumble/appyx/sandbox/client/interactorusage/InteractorNodeBuilder.kt
  samples/sandbox/src/main/kotlin/com/bumble/appyx/sandbox/client/navmodels/NavModelExamplesNode.kt
  samples/sandbox/src/main/kotlin/com/bumble/appyx/sandbox/ui/Color.kt
  samples/sandbox/src/main/kotlin/com/bumble/appyx/sandbox/ui/Theme.kt
Labels: samples

#218 Updated androidx core to 1.9.0
  CHANGELOG.md
  gradle/libs.versions.toml
Labels: enhancement

#165 Cards NavModel
  CHANGELOG.md
  documentation/index.md
  documentation/navmodel/cards.md
  libraries/core/src/main/kotlin/com/bumble/appyx/core/navigation/BaseNavModel.kt
  mkdocs.yml
  samples/app/build.gradle.kts
  samples/app/src/main/kotlin/com/bumble/appyx/app/node/samples/CardsExampleNode.kt
  samples/app/src/main/kotlin/com/bumble/appyx/app/node/samples/SamplesContainerNode.kt
  samples/common/.gitignore
  samples/common/build.gradle.kts
  samples/common/lint-baseline.xml
  samples/common/proguard-rules.pro
  samples/common/src/main/java/com/bumble/appyx/samples/common/profile/Profile.kt
  samples/common/src/main/java/com/bumble/appyx/samples/common/profile/ProfileCardNode.kt
  samples/common/src/main/res/drawable/halloween10.jpeg
  samples/common/src/main/res/drawable/halloween11.jpeg
  samples/common/src/main/res/drawable/halloween12.jpeg
  samples/common/src/main/res/drawable/halloween13.jpeg
  samples/common/src/main/res/drawable/halloween14.jpeg
  samples/common/src/main/res/drawable/halloween15.jpeg
  samples/common/src/main/res/drawable/halloween3.jpeg
  samples/common/src/main/res/drawable/halloween4.jpeg
  samples/common/src/main/res/drawable/halloween6.jpeg
  samples/common/src/main/res/drawable/halloween7.jpeg
  samples/common/src/main/res/drawable/halloween8.jpeg
  samples/common/src/main/res/drawable/halloween9.jpeg
  samples/common/src/main/res/values/colors.xml
  samples/navmodel-samples/lint-baseline.xml
  samples/navmodel-samples/src/main/kotlin/com/bumble/appyx/navmodel/cards/Cards.kt
  samples/navmodel-samples/src/main/kotlin/com/bumble/appyx/navmodel/cards/CardsElement.kt
  samples/navmodel-samples/src/main/kotlin/com/bumble/appyx/navmodel/cards/CardsOnScreenResolver.kt
  samples/navmodel-samples/src/main/kotlin/com/bumble/appyx/navmodel/cards/operation/CardsOperation.kt
  samples/navmodel-samples/src/main/kotlin/com/bumble/appyx/navmodel/cards/operation/IndicateLike.kt
  samples/navmodel-samples/src/main/kotlin/com/bumble/appyx/navmodel/cards/operation/IndicatePass.kt
  samples/navmodel-samples/src/main/kotlin/com/bumble/appyx/navmodel/cards/operation/PromoteAll.kt
  samples/navmodel-samples/src/main/kotlin/com/bumble/appyx/navmodel/cards/operation/TopCardOperation.kt
  samples/navmodel-samples/src/main/kotlin/com/bumble/appyx/navmodel/cards/operation/VoteLike.kt
  samples/navmodel-samples/src/main/kotlin/com/bumble/appyx/navmodel/cards/operation/VotePass.kt
  samples/navmodel-samples/src/main/kotlin/com/bumble/appyx/navmodel/cards/transitionhandler/CardsTransitionHandler.kt
  samples/sandbox/build.gradle.kts
  samples/sandbox/src/main/kotlin/com/bumble/appyx/sandbox/client/cardsexample/CardsExampleNode.kt
  samples/sandbox/src/main/kotlin/com/bumble/appyx/sandbox/client/navmodels/NavModelExamplesNode.kt
  samples/sandbox/src/main/kotlin/com/bumble/appyx/sandbox/client/spotlightadvancedexample/SpotlightAdvancedExampleNode.kt
  settings.gradle.kts
Labels: navmodel-impl, samples

#227 Cards improvements
  libraries/core/src/main/kotlin/com/bumble/appyx/core/navigation2/inputsource/DragProgressInputSource.kt
  samples/navmodel-samples/src/main/kotlin/com/bumble/appyx/navmodel2/cards/transitionhandler/CardsProps.kt
  samples/sandbox2/src/main/java/com/bumble/appyx/sandbox2/MainActivity.kt
  samples/sandbox2/src/main/java/com/bumble/appyx/sandbox2/navmodel2/DatingCards.kt
  samples/sandbox2/src/main/java/com/bumble/appyx/sandbox2/navmodel2/SpotlightExperiment.kt
Labels: enhancement, gestures

#231 Add a key to rememberTransitionScope to support dynamically changed transition handlers
  CHANGELOG.md
  libraries/core/src/main/kotlin/com/bumble/appyx/core/navigation/transition/ModifierTransitionHandler.kt
Labels: bug

#233 Return if operation is not applicable
  libraries/core/src/main/kotlin/com/bumble/appyx/core/navigation2/inputsource/DragProgressInputSource.kt
Labels: bug

#236 Sample app fixes
  samples/app/src/main/kotlin/com/bumble/appyx/app/node/cards/CardsExampleNode.kt
  samples/app/src/main/kotlin/com/bumble/appyx/app/node/onboarding/OnboardingContainerNode.kt
  samples/app/src/main/kotlin/com/bumble/appyx/app/node/samples/SampleItem.kt
  samples/app/src/main/kotlin/com/bumble/appyx/app/node/samples/SamplesContainerNode.kt
  samples/app/src/main/kotlin/com/bumble/appyx/app/ui/Shape.kt
  samples/navigation-compose/src/main/kotlin/com/bumble/appyx/sample/navigtion/compose/ComposeNavigationRoot.kt
Labels: enhancement, samples

#240 Sample app update
  samples/app/src/main/kotlin/com/bumble/appyx/app/composable/graph/nodeimpl/SimpleGraphNode.kt
  samples/app/src/main/kotlin/com/bumble/appyx/app/node/cards/CardsExampleNode.kt
  samples/app/src/main/kotlin/com/bumble/appyx/app/node/root/RootNode.kt
  samples/app/src/main/kotlin/com/bumble/appyx/app/node/samples/SamplesContainerNode.kt
  samples/app/src/main/kotlin/com/bumble/appyx/app/node/slideshow/WhatsAppyxSlideShow.kt
  samples/app/src/main/kotlin/com/bumble/appyx/app/node/slideshow/slide/app/ApplicationTree.kt
  samples/app/src/main/kotlin/com/bumble/appyx/app/node/slideshow/slide/app/StatefulNode1.kt
  samples/app/src/main/kotlin/com/bumble/appyx/app/node/slideshow/slide/app/StatefulNode2.kt
  samples/app/src/main/kotlin/com/bumble/appyx/app/node/slideshow/slide/modeldriven/ComposableNavigation.kt
  samples/app/src/main/kotlin/com/bumble/appyx/app/node/slideshow/slide/modeldriven/Intro.kt
  samples/app/src/main/kotlin/com/bumble/appyx/app/node/slideshow/slide/modeldriven/ModelDrivenIntro.kt
  samples/app/src/main/kotlin/com/bumble/appyx/app/node/slideshow/slide/modeldriven/NavModelTeaserNode.kt
Labels: enhancement, samples

#245 Fixed parcelling bug for navmodel samples
  samples/navmodel-samples/src/main/kotlin/com/bumble/appyx/navmodel/cards/Cards.kt
  samples/navmodel-samples/src/main/kotlin/com/bumble/appyx/navmodel/spotlightadvanced/SpotlightAdvanced.kt
Labels: bug

#248 Remove custom splash and use new Android API for Splash screen
  gradle/libs.versions.toml
  samples/app/build.gradle.kts
  samples/app/src/main/AndroidManifest.xml
  samples/app/src/main/kotlin/com/bumble/appyx/app/MainActivity.kt
  samples/app/src/main/kotlin/com/bumble/appyx/app/node/root/RootNode.kt
  samples/app/src/main/kotlin/com/bumble/appyx/app/node/samples/SamplesContainerNode.kt
  samples/app/src/main/res/drawable-xxxhdpi/appyx_text_black_s.png
  samples/app/src/main/res/drawable-xxxhdpi/appyx_text_white_s.png
  samples/app/src/main/res/values-night/themes.xml
  samples/app/src/main/res/values/themes.xml
Labels: enhancement, samples
