Repository bumble-tech/appyx, pull requests merged in 2022-09, with the labels that each got.

#127 Mark Node class as stable to allow compose compiler to infer stability of composable functions
  CHANGELOG.md
  core/src/main/kotlin/com/bumble/appyx/core/node/Node.kt
Labels: enhancement

#134 Make NodeView.kt interface and ParentNode class stable
  CHANGELOG.md
  core/src/main/kotlin/com/bumble/appyx/core/node/NodeView.kt
  core/src/main/kotlin/com/bumble/appyx/core/node/ParentNode.kt
Labels: enhancement

#163 Document ChildAware API
  documentation/apps/childaware.md
  documentation/apps/structure.md
  mkdocs.yml
Labels: documentation

#178 Cache integration point result if there are no subscribers and flush when they appear
  CHANGELOG.md
  libraries/core/src/main/kotlin/com/bumble/appyx/core/integrationpoint/requestcode/RequestCodeBasedEventStreamImpl.kt
  libraries/core/src/main/kotlin/com/bumble/appyx/core/node/Node.kt
  libraries/core/src/test/kotlin/com/bumble/appyx/core/children/ChildCreationTest.kt
  libraries/core/src/test/kotlin/com/bumble/appyx/core/lifecycle/ChildLifecycleTest.kt
  libraries/core/src/test/kotlin/com/bumble/appyx/core/lifecycle/ParentLifecycleTest.kt
  libraries/core/src/test/kotlin/com/bumble/appyx/core/navigation/upnavigation/UpNavigationTest.kt
  samples/app/src/main/kotlin/com/bumble/appyx/app/node/child/GenericChildNode.kt
  samples/sandbox/src/main/kotlin/com/bumble/appyx/sandbox/client/container/ContainerNode.kt
  samples/sandbox/src/main/kotlin/com/bumble/appyx/sandbox/client/integrationpoint/IntegrationPointExampleNode.kt
Labels: bug
