Repository bumble-tech/appyx, pull requests merged in 2023-01, with the labels that each got.

#315 Remove package from AndroidManifest.xml
  libraries/testing-junit4/src/main/AndroidManifest.xml
  libraries/testing-junit5/src/main/AndroidManifest.xml
  libraries/testing-unit-common/src/main/AndroidManifest.xml
  samples/app/build.gradle.kts
  samples/app/src/main/AndroidManifest.xml
  samples/sandbox/build.gradle.kts
  samples/sandbox/src/main/AndroidManifest.xml
Labels: cleanup, backwards-compatible

#314 Fix lifecycle issue and add missing tests
  CHANGELOG.md
  libraries/core/src/main/kotlin/com/bumble/appyx/core/FlowExt.kt
  libraries/core/src/main/kotlin/com/bumble/appyx/core/children/ChildAwareCallbackInfo.kt
  libraries/core/src/main/kotlin/com/bumble/appyx/core/children/ChildAwareImpl.kt
  libraries/core/src/main/kotlin/com/bumble/appyx/core/lifecycle/ChildNodeLifecycleManager.kt
  libraries/core/src/main/kotlin/com/bumble/appyx/core/node/ParentNode.kt
  libraries/core/src/test/kotlin/com/bumble/appyx/core/children/ChildAwareImplTest.kt
  libraries/core/src/test/kotlin/com/bumble/appyx/core/children/ChildAwareTestBase.kt
  libraries/core/src/test/kotlin/com/bumble/appyx/core/lifecycle/ChildLifecycleTest.kt
Labels: bug, backwards-compatible

#317 Clean up gradle catalogue and use compose BOM
  gradle/libs.versions.toml
  libraries/core/build.gradle.kts
  libraries/interop-ribs/build.gradle.kts
  libraries/testing-ui/build.gradle.kts
  samples/app/build.gradle.kts
  samples/common/build.gradle.kts
  samples/navigation-compose/build.gradle.kts
  samples/navmodel-samples/build.gradle.kts
  samples/sandbox/build.gradle.kts
Labels: build & CI

#325 Ensure node was built before using PermanentChild API
  CHANGELOG.md
  libraries/testing-ui/src/main/kotlin/com/bumble/appyx/testing/ui/rules/AppyxViewTestRule.kt
Labels: bug, backwards-compatible
