Repository bumble-tech/appyx, pull requests merged in 2023-05, with the labels that each got.

#425 Up navigation interop
  CHANGELOG.md
  libraries/interop-ribs/src/androidTest/kotlin/com/bumble/appyx/interop/ribs/InteropNodeImplTest.kt
  libraries/interop-ribs/src/androidTest/kotlin/com/bumble/appyx/interop/ribs/RibsNode.kt
  libraries/interop-ribs/src/main/kotlin/com/bumble/appyx/interop/ribs/InteropBuilder.kt
  libraries/interop-ribs/src/main/kotlin/com/bumble/appyx/interop/ribs/UpHandlingAppyxIntegrationPoint.kt
Labels: bug, backwards-compatible

#424 PermanentModel.kt restore state correctly
  appyx-interactions/common/src/commonMain/kotlin/com/bumble/appyx/interactions/permanent/PermanentInteractionModel.kt
  appyx-interactions/common/src/commonMain/kotlin/com/bumble/appyx/interactions/permanent/PermanentModel.kt
  appyx-interactions/common/src/commonTest/kotlin/com/bumble/appyx/interactions/permanent/PermanentModelTest.kt
  appyx-navigation/src/main/kotlin/com/bumble/appyx/navigation/node/ParentNode.kt
  demos/appyx-navigation/src/main/kotlin/com/bumble/appyx/navigation/node/permanentchild/PermanentChildNode.kt
Labels: bug

#431 Multiplatform utils
  appyx-components/backstack/common/src/commonMain/kotlin/com/bumble/appyx/components/backstack/BackStackModel.kt
  appyx-components/backstack/common/src/commonMain/kotlin/com/bumble/appyx/components/backstack/operation/NewRoot.kt
  appyx-components/backstack/common/src/commonMain/kotlin/com/bumble/appyx/components/backstack/operation/Pop.kt
  appyx-components/backstack/common/src/commonMain/kotlin/com/bumble/appyx/components/backstack/operation/Push.kt
  appyx-components/backstack/common/src/commonMain/kotlin/com/bumble/appyx/components/backstack/operation/Replace.kt
  appyx-components/demos/common/src/commonMain/kotlin/com/bumble/appyx/components/demos/cards/CardsModel.kt
  appyx-components/demos/common/src/commonMain/kotlin/com/bumble/appyx/components/demos/cards/operation/VoteLike.kt
  appyx-components/demos/common/src/commonMain/kotlin/com/bumble/appyx/components/demos/cards/operation/VotePass.kt
  appyx-components/demos/common/src/commonMain/kotlin/com/bumble/appyx/components/demos/promoter/PromoterModel.kt
  appyx-components/demos/common/src/commonMain/kotlin/com/bumble/appyx/components/demos/promoter/operation/AddFirst.kt
  appyx-components/internal/common/src/commonMain/kotlin/com/bumble/appyx/components/internal/testdrive/TestDriveModel.kt
  appyx-components/internal/common/src/commonMain/kotlin/com/bumble/appyx/components/internal/testdrive/operation/MoveTo.kt
  appyx-components/internal/common/src/commonMain/kotlin/com/bumble/appyx/components/internal/testdrive/operation/Next.kt
  appyx-components/spotlight/common/src/commonMain/kotlin/com/bumble/appyx/components/spotlight/SpotlightModel.kt
  appyx-components/spotlight/common/src/commonMain/kotlin/com/bumble/appyx/components/spotlight/operation/Activate.kt
  appyx-components/spotlight/common/src/commonMain/kotlin/com/bumble/appyx/components/spotlight/operation/First.kt
  appyx-components/spotlight/common/src/commonMain/kotlin/com/bumble/appyx/components/spotlight/operation/Last.kt
  appyx-components/spotlight/common/src/commonMain/kotlin/com/bumble/appyx/components/spotlight/operation/Next.kt
  appyx-components/spotlight/common/src/commonMain/kotlin/com/bumble/appyx/components/spotlight/operation/Previous.kt
  appyx-components/spotlight/common/src/commonMain/kotlin/com/bumble/appyx/components/spotlight/operation/UpdateElements.kt
  appyx-interactions/common/build.gradle.kts
  appyx-interactions/common/src/androidMain/kotlin/com/bumble/appyx/interactions/platform.kt
  appyx-interactions/common/src/commonMain/kotlin/com/bumble/appyx/interactions/core/Element.kt
  appyx-interactions/common/src/commonMain/kotlin/com/bumble/appyx/interactions/core/model/transition/BaseTransitionModel.kt
  appyx-interactions/common/src/commonMain/kotlin/com/bumble/appyx/interactions/core/model/transition/Operation.kt
  appyx-interactions/common/src/commonMain/kotlin/com/bumble/appyx/interactions/permanent/PermanentModel.kt
  appyx-interactions/common/src/commonMain/kotlin/com/bumble/appyx/interactions/permanent/operation/AddUnique.kt
  appyx-interactions/common/src/commonMain/kotlin/com/bumble/appyx/interactions/platform.kt
  appyx-interactions/common/src/commonTest/kotlin/com/bumble/appyx/interactions/core/TestTransitionModel.kt
  appyx-interactions/common/src/desktopMain/kotlin/com/bumble/appyx/interactions/platform.kt
  appyx-interactions/common/src/jsMain/kotlin/com/bumble/appyx/interactions/platform.kt
  settings.gradle.kts
  utils/multiplatform/build.gradle.kts
  utils/multiplatform/src/androidMain/kotlin/com/bumble/appyx/utils/multiplatform/Parcelize.kt
  utils/multiplatform/src/commonMain/kotlin/com/bumble/appyx/utils/multiplatform/Parcelable.kt
  utils/multiplatform/src/desktopMain/kotlin/com/bumble/appyx/utils/multiplatform/Parcelable.kt
  utils/multiplatform/src/jsMain/kotlin/com/bumble/appyx/utils/multiplatform/Parcelable.kt
Labels: appyx-navigation

#437 Check nullability before calling ParenNode's performUpNavigation method
  appyx-navigation/src/main/kotlin/com/bumble/appyx/navigation/node/Node.kt
Labels: bug

#443 Fix bug when updating elements with different size compared to the current set of elements
  appyx-components/spotlight/common/src/commonMain/kotlin/com/bumble/appyx/components/spotlight/operation/UpdateElements.kt
  appyx-components/spotlight/common/src/commonTest/kotlin/com/bumble/appyx/components/spotlight/model/SpotlightModelTest.kt
  appyx-components/spotlight/common/src/commonTest/kotlin/com/bumble/appyx/components/spotlight/restore/SpotlightRestoreTest.kt
Labels: bug
